// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZP6UQCZUkDdm5RpaqwvLQR2PgErOMKYI',
    appId: '1:772253791954:web:bd777a55004e3c49849f0b',
    messagingSenderId: '772253791954',
    projectId: 'my-content-3b275',
    authDomain: 'my-content-3b275.firebaseapp.com',
    storageBucket: 'my-content-3b275.firebasestorage.app',
    measurementId: 'G-EX5J641827',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiur-Z3WtsaiO8DRzfBC-BL0VrUXkXuVQ',
    appId: '1:772253791954:android:353f5461600ce576849f0b',
    messagingSenderId: '772253791954',
    projectId: 'my-content-3b275',
    storageBucket: 'my-content-3b275.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiopm9a-ZHhVuC196mEXnyw5iKWBc9e10',
    appId: '1:772253791954:ios:b56a6aff14411410849f0b',
    messagingSenderId: '772253791954',
    projectId: 'my-content-3b275',
    storageBucket: 'my-content-3b275.firebasestorage.app',
    iosBundleId: 'com.example.recentsContent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiopm9a-ZHhVuC196mEXnyw5iKWBc9e10',
    appId: '1:772253791954:ios:b56a6aff14411410849f0b',
    messagingSenderId: '772253791954',
    projectId: 'my-content-3b275',
    storageBucket: 'my-content-3b275.firebasestorage.app',
    iosBundleId: 'com.example.recentsContent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZP6UQCZUkDdm5RpaqwvLQR2PgErOMKYI',
    appId: '1:772253791954:web:56b24f31ad9f72d2849f0b',
    messagingSenderId: '772253791954',
    projectId: 'my-content-3b275',
    authDomain: 'my-content-3b275.firebaseapp.com',
    storageBucket: 'my-content-3b275.firebasestorage.app',
    measurementId: 'G-M1MG33ES5Z',
  );
}
